name: check-open-all-stores-from-catalog

on: 
  workflow_dispatch:

jobs:
  auth-check:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          mamba-version: '*'
          channel-priority: strict
          auto-update-conda: false
          python-version: "3.9"
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: >
          mamba install gcsfs intake-esm xmip xarray zarr dask
      - id: 'upload-script'
        run: python check-open-stores.py
      - id: 'save-error-report'
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.txt
