name: check-open-all-stores-from-catalog

on: 
  workflow_dispatch:

jobs:
  auth-check:
    timeout-minutes: 360
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: >
          pip install gcsfs tqdm pandas intake-esm xmip xarray zarr dask
      - id: 'upload-script'
        run: python check-open-stores.py
      - id: 'save-error-report'
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.txt
