name: check-open-all-stores-from-catalog

on: 
  workflow_dispatch:

jobs:
  auth-check:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: >
          pip install gcsfs intake-esm xmip xarray zarr dask
      - id: 'upload-script'
        run: python check-open-stores.py
      - id: 'save-error-report'
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.txt
